// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCTDEu8f142d-Ian-anVIQ8fOli__qP1lU',
    appId: '1:165336968557:web:6e7154f0d1f2aa942d7e64',
    messagingSenderId: '165336968557',
    projectId: 'farmatech-3d87b',
    authDomain: 'farmatech-3d87b.firebaseapp.com',
    storageBucket: 'farmatech-3d87b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDO7qyet1KuzCowTHkDV-CzuJNqO_2ePsM',
    appId: '1:165336968557:android:6b78d2c0cd6727002d7e64',
    messagingSenderId: '165336968557',
    projectId: 'farmatech-3d87b',
    storageBucket: 'farmatech-3d87b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBC1aWgYQbZY_LFxWZXadX67iUXtSdZhNI',
    appId: '1:165336968557:ios:9908862ad5d99bc32d7e64',
    messagingSenderId: '165336968557',
    projectId: 'farmatech-3d87b',
    storageBucket: 'farmatech-3d87b.appspot.com',
    iosClientId: '165336968557-q5a5gfuk0oagp2rovegob4qe786o4klk.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterSqliteAuthApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBC1aWgYQbZY_LFxWZXadX67iUXtSdZhNI',
    appId: '1:165336968557:ios:9908862ad5d99bc32d7e64',
    messagingSenderId: '165336968557',
    projectId: 'farmatech-3d87b',
    storageBucket: 'farmatech-3d87b.appspot.com',
    iosClientId: '165336968557-q5a5gfuk0oagp2rovegob4qe786o4klk.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterSqliteAuthApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCTDEu8f142d-Ian-anVIQ8fOli__qP1lU',
    appId: '1:165336968557:web:e4ca1025a41509232d7e64',
    messagingSenderId: '165336968557',
    projectId: 'farmatech-3d87b',
    authDomain: 'farmatech-3d87b.firebaseapp.com',
    storageBucket: 'farmatech-3d87b.appspot.com',
  );

}